### ISSUE TITLE
304 Not Modified http code request give this error

### ISSUE THREAD

**Issue by DWboutin** [visionmedia/superagent#1096]
The first time that i make the request, it gives me an HTTP code `200`. But if i reload, it gives me a HTTP code `304 Not Modified` (which must be correct) and superagent throw an error.

`client.js:501 Uncaught (in promise) Error: Unsuccessful HTTP response(…)`

Is it correct!?

Version `1.7.1` works perfectly, but the latest gives me this error. (I rolled back, because i never saw this in the old version)

**Comment by pornel** [comment]
AFAIK this behavior did not change since 1.7. Only 2xx responses are treated as success. We treat 304 as an error, because it does not contain response body, and is not guaranteed to have all the usual HTTP headers of the response, so the usual properties like `response` object would be useless (with no `response.body`, `response.text`, etc.).

**Comment by DWboutin** [comment]
Why it doesn't trigger the error with the `1.7.1` version? Is it possible the treat 304 as a 2xx response? What can cause an http code 304 with superagent? I poke my server-side which is in the same port of my website, first request gives me a 200, when reloading it gives me a 304 but it works...

**Comment by pornel** [comment]
The 304 response is sent by the server when it sees matching `If-Modified-Since` or `If-None-Match` headers in the request. It's likely to happen when you request URL that is cached by the browser.

You should still see the same error in 1.7.1, because that change has been made in 1.0.0:

1.0.0 / 2015-03-08
==================

 * All non-200 responses are treated as errors now. (The callback is called with an error when the response has a status < 200 or >= 300 now. In previous versions this would not have raised an error and the client would have to check the `res` object. See [#283](https://github.com/visionmedia/superagent/issues/283).

**Comment by DWboutin** [comment]
> You should still see the same error in 1.7.1, because that change has been made in 1.0.0:

If i don't see it? Cause i really don't. And if i'm with the latest version, it stop the request, not with the 1.7.1

**Comment by pornel** [comment]
It's possible that some other change caused the server to start returning 304, but I'm 100% sure that once the server sends 304, all versions past 1.0 will behave the same.
