### ISSUE TITLE
How can I pass my own http.agent in a request

### ISSUE THREAD

**Issue by abhagupta** [visionmedia/superagent#1130]
I need to pass my own proxy agent in a request.  Meaning, all the requests inside my application should use my customized agent which makes the requests pass through a proxy. Something similar to `agent` object in `http.request`.  Is there a easy way to do it?

**Comment by focusaurus** [comment]
One way that is pretty simple in my opinion is just use an alternate initial request function in your application:

```js
const request = require('superagent')

function appRequest (method, url) {
  return request(method, url).agent(myAgent)
}
```

Use that throughout your application instead of directly calling the superagent request function. The code throughout your application can then use the full superagent API to configure requests before sending them.

**Comment by abhagupta** [comment]
Thanks @focusaurus . Above worked but we are using `superagent` extensively and using this would require changes at multiple places with not very clean solution. Is there a way the `http.agent`  can be easily set on the underlying `http` object cleanly? Something that happens in `request` npm.  I can debug `superagent` myself and send a PR if you can give me some pointers.

**Comment by focusaurus** [comment]
Maybe you'd prefer monkey patching like this:

```js
const superagent = require('./')
const http = require('http')

const myAgent = new http.Agent()

const OrigRequest = superagent.Request
superagent.Request = function RequestWithAgent (method, url) {
  const req = new OrigRequest(method, url)
  return req.agent(myAgent)
}
const b = superagent.get('/')
console.log(b._agent)
```

Keep in mind someone reading your code, seeing what looks like unmodified superagent use but getting different behavior may feel that a monkey patch in some other file in the code base is "not very clean" and causes surprise in the bad sense.

@pornel What do you think about emitting an event when a new request is initialized so folks could do `superagent.on('init', customize)`?

**Comment by abhagupta** [comment]
Thanks @focusaurus . I will explore this as well.  However, what I am really trying to do is making use of `http.globalAgent`, override it with my proxy agent, and pass it to the superagent  something like this 
```
var http = require('http');
var HttpProxyAgent = require('http-proxy-agent');
module.exports = myAgent = http.globalAgent =  new HttpProxyAgent('http://127.0.0.1:8442');

var options = {
    host: 'www.google.com',
    port: 80,
    path: '/index.html',
    agent: myAgent
};

http.get(options, function( res){
    res.on("data", function(chunk){
        console.log('BODY: ' + chunk);

    })
})
```

If `superagent` has an option to pass along an agent object to request, I will have to do just one change. 

The result that I am expecting is, if I encapsulate my application by an outer module which sets `globalAgent` and run both in same  process (like `node index.js myapplication` )  then all http requests going out in my application will have the `myAgent` which should make it go through the proxy running at `http://127.0.0.1:8442`. Is it something feasible at all?

**Comment by pornel** [comment]
I think we could add more cross-request customizability via `superagent.agent()` methods. That creates an instance that an app could safely change.

I'd rather not have any global `superagent.on`, because then libraries couldn't safely use superagent without risking interfering with each other.

**Comment by pszabop** [comment]
@pornel cross-request customizability would be very nice.  For example, need to be able to add to every request a JWT header, an CSRF header, etc..  A hook in in `superagent.agent()` would be very nice for doing that.

**Comment by pornel** [comment]
It's done! `.agent()` now supports `.set()`, etc.

**Comment by pornel** [comment]
As for the original question:

```js
const superagent = request('superagent').agent(myAgent);
```

it will create a copy of superagent that uses `myAgent` for all requests.

**Comment by pszabop** [comment]
well, one of the CSRF solutions involves copying a token from a  cookie (or local storage) to a header on every request.  Having to call .set() on every request and figuring out a place to store the token while I"m passing around references to the agent to helper functions is proving problematic.  Have to support nodejs and browser...

**Comment by pornel** [comment]
You can do `agent().use(yourCallback)` and the callback will be called with the request object every time a new request is created. From there you can set headers and listen to redirects and responses.

**Comment by pszabop** [comment]
1.  have to use `supertest` because simply passing the expressjs app to your agent function doesn't work.  I'm not using `supertest` for any other feature except for that.
1.  `supertest` won't accept your plugins.  Well, at least they won't accept `supertest-use` which is the one I want.
1.  If I could get `supertest-use` to work, I don't know how to access the cookie jar in the agent.

**Comment by pornel** [comment]
The agent is strictly for Node's HTTP agent. It's a different API with a different level of abstraction than express.

I can't help with supertest, unfortunately. It's a weird situation that it's a separate project implemented by other people.

**Comment by pszabop** [comment]
leaving aside `supertest`, how would you access the agent's nodejs cookie jar inside of the `use()` callback?   Are the cookies on the request structure?

**Comment by pornel** [comment]
Oh, we don't have a stable api for the cookie jar. You'd need to keep track of them yourself (see [how agent does it](https://github.com/visionmedia/superagent/blob/master/lib/node/agent.js))

**Comment by pszabop** [comment]
Yes, I saw the cookie code.  Was hoping to not have to rewrite it all.

I'm kind of flummoxed.   CSRF is at least an 8 year old problem, yet AFAICT AngularJS is the only agent out there that has native support for putting a cookie into a header in a natural fashion.   (natural, meaning, as natural as cookies are added currently by `superagent.agent()` )

Everything else appears to be extremely awkward.  I'm passing handles to a `supergent.agent()` around and the cookies currently go with them.  I'd have to modify all my functions to accept a cookie jar handle, or keep a global cookie jar around separately instead of in the agent, or ???.  That doesn't seem like the right way to do things...

**Comment by pornel** [comment]
Passing the agent (result of `superagent.agent()`) around is the right solution. It's like dependency injection. 

If you expect to modify behavior of superagent straight from `require('superagent')`, then that's a no-no, because this is a global variable, and it would create a shared mutable state.

**Comment by pszabop** [comment]
agreed, I want to put the cookies into (result of `superagent.agent()` and then put those cookies into the headers `Authorization` or `X-CSRF` on all outbound HTTP requests.
