### ISSUE TITLE
querystring goofed on one item arrays - indices: false?

### ISSUE THREAD

**Issue by contra** [visionmedia/superagent#1224]
```js
request.get('/test').query({ a: [ 'yo' ] })
```

will come out as `/test?a=yo` which is incorrect, and gets parsed by the server as `{ a: 'yo' }`

This is because for some reason (I looked long and hard to find where/why it was added) the qs.stringify param on node has `indices: false` which breaks empty and single item arrays.

Solution is to remove that option so querystrings are created normally. Can send a PR if you want.

**Comment by pornel** [comment]
This is intentional. It's not incorrect, since interpretation of query stings is up to the server, and there never was any guarantee that JSON can be losslessly expressed as HTTP query strings.

Superagent specifically doesn't automatically add `[]` to query strings, because it supports query strings such as `test?a=1&a=2`, which are valid and used by some servers.

If you'd like URL `test?a[]=1&a[]=2`, then use `.query({'a[]': [1,2])`.

**Comment by contra** [comment]
@pornel Yeah, I get that `a=1&a=2` is a perfectly fine way to serialize an array with more than one item and the server will parse it just fine. If I'm understanding you right, this is a wontfix because you don't want to break servers that don't understand `[]` but don't mind breaking this case for servers that do.

Is there any way to override the qs function globally on superagent (either via config, exposed prototype, or a plugin) instead of doing it for every request? I'll happily make a plugin if it's possible to override it.

Might be worth putting a note somewhere that superagent serializes querystrings in a lossy way, this was a confusing bug to track down a few levels up in the stack.

**Comment by pornel** [comment]
If you want global, then you can patch or replace `superagent.Request` with a query method that you want.

For local behaviour, a `.use(plugin)` would work, the plugin could similarly patch the .query method (serialize using your settings, pass a string to super method).
