### ISSUE TITLE
.set('Authorization', 'Bearer perm: *********') doesn't work

### ISSUE THREAD

**Issue by qwerty2323** [visionmedia/superagent#1319]
I am managing YouTrack via http-client based on `superagent@3.8.1`
Following [YouTrack guide: ](https://www.jetbrains.com/help/youtrack/standalone/Log-in-to-YouTrack.html)
```js
const agent = require('superagent');
return agent
  .get('yt.*****.ru/rest/admin/project')
  .set('Authorization', 'Bearer perm:********************')
  .then(response => {
    console.log(response.status);
  })
  .catch(response => console.log(`Error ${response}`));
```
Expected: 200 -- Success
Actual: 401 -- Unauthorized.

It works correctly on `3.8.0` version and older

**Comment by pornel** [comment]
Does it work in 3.7.0?

**Comment by qwerty2323** [comment]
Yes, It works in 3.8.0 & older.

**Comment by pornel** [comment]
So the problem is caused redirects to another domain. (you can use `.on('redirect', cb)` to inspect them).

Change in 3.8.1 is considered a security issue, because previously the `Authorization` would have been sent to every domain redirected to.

Superagent doesn't have a way to know which domains are supposed to get `Authorization`, so it plays safe and allows it only on the original request.
