### ISSUE TITLE
Provide minified version in the npm package

### ISSUE THREAD

**Issue by windware** [visionmedia/superagent#1340]
It would help reduce the bundled size done with bundlers while under development where no minification takes place.

**Comment by kornelski** [comment]
I'd rather not publish two versions/one version with two implementations. That adds overhead to publishing, documentation and bug reporting.

During development a usual concern is to have source code readable in order to be able to use breakpoints, step through in debugger, etc.

If you need smaller packages during development, I suggest enabling minification in your dev builds.

**Comment by windware** [comment]
It's pretty common that packages usually come with app.js and app.min.js. It's just a matter of creating a minified version of exactly the same file. What kind of overhead are you mentioning when using either of them yields completely same results?

Of course I can minimize when it goes to production but development is all about speed and I'd rather want the packages come minified than, minify them every time I bundle it up during development and I'm assuming the libraries that I use are not too buggy and won't require for me to look at the human readable versions until necessary.

**Comment by kornelski** [comment]
We could minify the browser build we make and bundle in the nodejs package. However, that build is only for the front-end `<script>`, and not for common JS usage.
