### ISSUE TITLE
How to inspect a request's data without using `._data`?

### ISSUE THREAD

**Issue by nicogreenarry** [visionmedia/superagent#1391]
Is there a way to inspect the data on a request (i.e. the data attached by `.send(data)`) without using the private-ish `._data` property of the request?

We'd like to be able to throw an error if a request's method is "GET" and it also has data.

**Comment by kornelski** [comment]
No, superagent is supposed to be for performing requests, not for representing them. 

If you're trying to write a test/assertion to catch potential bugs, then I guess there's no better way. Otherwise you should ensure in your application logic that you don't set unwanted request data in the first place.
