### ISSUE TITLE
code is  translation. why?

### ISSUE THREAD

**Issue by Yangk030208** [visionmedia/superagent#1410]
When I use this library, return such code, it seems to be translation（I know translation is inaccurate, but I don't have a better word  >_<  ）, I want to know why? Who can tell me, thank you。

"superagent": "^3.8.3"
"nodejs": "9.8.0"

![image](https://user-images.githubusercontent.com/23301914/45143937-3dfb9c80-b1ef-11e8-8f3a-d6f7bebbba92.png)

**Comment by kornelski** [comment]
I assume you're worried about text being presented as `\\x63` and not an actual character.

This seems fine to me. It's just presented this way, because you've printed it from an object (presumably using console.log or similar).

If characters aren't correct, it may be because they use a different encoding than UTF-8. We only support UTF-8 and do not plan to support anything else.
