### ISSUE TITLE
In .send(obj), obj's toJSON method is not called

### ISSUE THREAD

**Issue by hasahmed** [visionmedia/superagent#1464]
I have an object that has a circular property. Because of that I need a `toJSON` method that handles that particular field appropriately. Super agents `send` method doesn't call my objects `toJSON` method and therefore the call to `JSON.strigify` inside of superagent its self throws an error.

I attempted to fix this myself by calling `data.toJSON` inside of `request-base.js:570` when the properties are copied into the requests data, but this lead to the server responding with `Rejected` later down the line. 

Here are the lines that I attempted to add

```javascript
/* lib/request-base.js  */
  if (isObj && isObject(this._data)) {
    if (data.toJSON) data = data.toJSON(); // my added line (leads to failure later)
    for (var key in data) {
      this._data[key] = data[key];
    }
...
```

**Comment by niftylettuce** [comment]
PR welcome

**Comment by hasahmed** [comment]
Yeah I tried to get it working, but it was quite in the weeds. When I finally figured out where it was should be called and added the code it caused an error. I'll post the error here if I ever get back around to checking it out again.

**Comment by niftylettuce** [comment]
@hasahmed 	I will release fix, one sec

**Comment by niftylettuce** [comment]
@hasahmed 	please try v5.0.9 released to npm, `npm install superagent@latest`

**Comment by MatthewHerbst** [comment]
Note: this change caused an unintentional library behavior change due to the new upstream dependency. Objects passed to `superagent` no longer have their `.toJSON` method called if it exists. This means that if users of `superagent` were relying on this functionality (as we were), they now need to call the `.serialize` and manually call the `.toJSON` method there.

I have an open issue upstream related to this: https://github.com/davidmarkclements/fast-safe-stringify/issues/46
