### ISSUE TITLE
double callback

### ISSUE THREAD

**Issue by willkan** [visionmedia/superagent#464]
I have compared the code of the tag 0.18.0 and the master.

I found that  current version handle error in a wrong way when watching the 'response' event.(The code is from line 881)

Firstly, module `parse` has used `try catch` inside, no need to `try catch` the json parse error when using the `parse` function.

Secondly, when `parse` callback an error, `self.callback(err)` will cause double callback, because superagent will callback automatically.

**Comment by englercj** [comment]
I am seeing this issue on `1.2.0` I think it is due to error handling again in the response parsing:

https://github.com/visionmedia/superagent/blob/master/lib/node/index.js#L955

This line doesn't return so it calls the callback and processing continues. That means that later an end listener is registered and that calls the callback again.

**Comment by 642250185** [comment]
So how do you solve this problem?
