### ISSUE TITLE
How can i get a javascript file content

### ISSUE THREAD

**Issue by zackwoo** [visionmedia/superagent#523]
```js
var request = require('superagent');
request
    .get('http://libs.baidu.com/jquery/1.8.3/jquery.min.js')
    .end(function (err, res) {
        console.log(res.text)
    })
```
I just get a undefined for res.text

**Comment by defunctzombie** [comment]
Is this on the client or the server?

**Comment by zackwoo** [comment]
on the server

**Comment by magicdawn** [comment]
```js
require('superagent').get('http://libs.baidu.com/jquery/1.8.3/jquery.min.js').pipe(process.stdout);
```
we can see the correct result.

Since the return mime type as `application/x-javascript`. so it's not buffered. use `.buffer(true)` to explicit buffer text.
```js
> void request.get('http://libs.baidu.com/jquery/1.8.3/jquery.min.js').buffer(true).end(function(err,res){ console.log(res.text.length) })
undefined
> 93637
```

PS: consider to use `['js','css','txt'....].indexOf(path.extname(url).slice(1))` to reimplement `isText` function.
https://github.com/visionmedia/superagent/blob/master/lib/node/index.js#L1047

PPS: 百度!居然还 x- ,Obsolete
http://stackoverflow.com/questions/9664282/difference-between-application-x-javascript-and-text-javascript-content-types

**Comment by zackwoo** [comment]
thank you
