### ISSUE TITLE
Range of status codes for error is problematic

### ISSUE THREAD

**Issue by aaronshaf** [visionmedia/superagent#613]
To many of us 400-level errors are _not_ actual errors. Sometimes they represent a desired state. This is problematic: 

```if (res.status >= 200 && res.status < 300)``` https://github.com/visionmedia/superagent/blob/master/lib/client.js#L480

Can we please at least make the status code range for errors configurable?

**Comment by defunctzombie** [comment]
I think configurable range is something that would be nice. I would entertain adding such an API.

**Comment by kmalakoff** [comment]
This change would need to handled very carefully. 

If any user of superagent can re-define the range globally, they may unintentionally break libraries they use that also have expectations on range. That could lead to library writers having to query the range to program defensibly against uncertain configuration.

To properly implement this, changing the range could necessitate the ability to create instances of superagent each with their own configurations (https://github.com/visionmedia/superagent/issues/591). 

Alternatively, the range could be set on individual requests, but that could be cumbersome.

Finally, we could just go back to the 0.x API and more strictly limit superagent to the transport layer instead of mixing in logic that is best left in the application/user-land.

**Comment by defunctzombie** [comment]
This would not be global but per instance. We already have Apis for per
instance so this is not hard at all.

**Comment by kmalakoff** [comment]
Interesting. Maybe this should be the answer for range mapping in general. 

If you could have people who want it add it to their request instances using existing mechanisms (add it to their instances) or those of us who don't want it, to be able to ignore the setting (skip it) or those who want it differently, set a different mapping (add It with a different range), that might make everyone happy rather than making the decision for users of superagent.

Or you have the current default range mapper added to each instance and provide a mechanism to clear it or set a different rangeMap function per instance.

If instance-based configuration is the way forward, we could create our own factory function for requests that set up instance defaults like disabling range mapping. 

Would you consider rather than using an existing monkey-patching API, adding a specific API for range mapping?

**Comment by defunctzombie** [comment]
@aaronshaf @kmalakoff take a look at https://github.com/visionmedia/superagent/pull/617 and share your thoughts.

@kmalakoff we could think about doing something global but I think your factory approach is better for the cases of creating custom request instances.

My general thoughts on this honestly are that you shouldn't be making agent instances all over your codebase anyway and requests (whether for APIs or whatnot) typically funnel through request methods you setup yourself scoped for the requirements. Obviously not everyone does that but the things I have written that end up doing http requests tend towards all calling a single "request" point eventually to avoid hunting down request code all over the app.

**Comment by kmalakoff** [comment]
Reviewed https://github.com/visionmedia/superagent/pull/617 and it looks good.

We internally have an agent factory that takes a Request class and some options and we have started to use it more (three concrete cases: retry, file uploader with retries, multi-step image uploader with retries). I'd probably add one more for superagent with the acceptedStatus default off.

We haven't tackled the global settings problem since it would require monkey-patching suepragent so probably instances work just fine if we use our own factory.

**Comment by thanpolas** [comment]
400 is an expected response, new behavior returning an error broke tests, downgraded to 0.21.0

On top of that, the `res` object was attached on the error object vs as the second argument.

**Comment by jprichardson** [comment]
I support going back to the `0.x` API. Returning an `error` for non-2xx status codes seems silly IMHO.

**Comment by elmigranto** [comment]
> API. Returning an error for non-2xx status codes seems silly

Unless someone uses HTTP as a transport and always returns 200.
