### ISSUE TITLE
`request.agent()` is not documented

### ISSUE THREAD

**Issue by olalonde** [visionmedia/superagent#658]
I couldn't find any information about `request.agent()` in the docs or README.md file.

**Comment by alex94puchades** [comment]
It's not documented because it is not available on the client build (see #729). Agents are used by the http module available on the server build. AFAIK, an equivalent does not exist for XHR, which is used on the client build, and adding a shim has not been discussed yet (I wouldn't have high hopes given browserland module size paranoia) xdd

Anyway, could you please describe your issue at #690? We're planning to reduce server-browser differences as one of our after-summer purposes (and as always PR are welcome and **strongly** appreciated)

**Comment by olalonde** [comment]
#690 wasn't my issue. I was just curious why it wasn't documented as I was using it in my app IIRC and wasn't sure if it was safe to do.
