### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by crypti** [visionmedia/superagent#682]
I run 112 tests, all tests using superagent. Sometimes happened this message for random api calls.
 
Uncaught TypeError: undefined is not a function
      at Socket.socketOnEnd [as onend] (http.js:1572:9)
      at _stream_readable.js:943:16

**Comment by crypti** [comment]
Why closed?

**Comment by ajnisbet** [comment]
I'm guessing because you didn't provide any information about your issue.

If you want to help, reduce your code to the [minimum amount that still produces an error](https://en.wikipedia.org/wiki/Minimal_Working_Example). Then post that code, the command you used to run it, the version of superagent you used, and the complete stacktrace.
