### ISSUE TITLE
Piping response of POST not writing to writeStream

### ISSUE THREAD

**Issue by johnmanong** [visionmedia/superagent#684]
I might be crazy, but the below code snippet does not seem work for me. `res.body` is a valid buffer and I can manually write to the stream with it, but I'm confused as to why pipe doesn't seem to be working.

```
// in a node env

var outStream = fs.createWriteStream('output.png');
  var req = superagent.post('http://pngcrush.com/crush')
                      .attach('input', 'filename.png');

  req.end(function(err, res) {
    res.pipe(outStream);  // why you no work, outStream still empty
  });
```

**Comment by mijie1023** [comment]
req.end(function(err, res) {
   // console.log(res.body);

   fs.writeFile('test.png', res.body, function(err) {
      console.log('Error: ' + err);
   });
});

**Comment by Enet4** [comment]
Bumping this dormant issue because an [SO question](http://stackoverflow.com/q/38478034/1233251) emerged with the same problem. I've just answered it too. Basically, right now one should pipe the request object instead of the obtained response.

Unless you wish to consider improving the documentation on how a response object should not be treated as a readable stream or actually making the readable stream part of the public API, this issue can be closed.

**Comment by pornel** [comment]
The `.end()` callback is called *after* piping has *ended* and is no longer possible.

You can't use both `.end()` and `.pipe()`. Only one of them is possible at a time.

**Comment by Enet4** [comment]
> The `.end()` callback is called after piping has ended and is no longer possible.
>
> You can't use both `.end()` and `.pipe()`. Only one of them is possible at a time.

Note that neither I nor the questions suggest doing both `end()` and `pipe()` on the request, but rather `end` the request and `pipe` the response, which is actually not that far out to assume the possibility. A small statement [in this section](http://visionmedia.github.io/superagent/#piping-data) would be nice to include.

**Comment by pornel** [comment]
When you call `.end()` then superagent takes response stream pipe, collects all of its data in `res.body`, and waits for the pipe to finish sending data.

The callback in `.end()` is called after response stream pipe has finished and closed. At this point it's guaranteed that it's not possible to pipe anything anymore, because all pipes have ended and closed.

**Comment by catc** [comment]
I'm still a bit confused by piping with superagent. I opened a [question](http://stackoverflow.com/questions/38838281/piping-readable-stream-using-superagent) on stack overflow if anyone could provide some clarification.

**Comment by pornel** [comment]
cc #1188
