### ISSUE TITLE
this.xhr.getResponseHeader('content-type') returns empty with react-native >0.5

### ISSUE THREAD

**Issue by alinz** [visionmedia/superagent#696]
I have been struggling with why all my apis start to fail after upgrading to `react-native` 0.5 and above. What I found is that, after upgrading `getResponseHeader('content-type')` returns null.

refer #181

**Comment by defunctzombie** [comment]
bug with react-native not this library

**Comment by alinz** [comment]
@defunctzombie I was the early adaptors of superagent. However, I still believe that overriding the header blindly is not a good idea. What I have done with this PR is checking the header value and if there is something, then override it. It might applicable to other venders as well. 

I'm not pushing this but I would like you to think about it one more times and give me a good reason why it is ok to override the header in your own way?

thanks

**Comment by defunctzombie** [comment]
Is this still not fixed in react-native? I just don't follow that this is broken behavior. The function call has a definition on what it should return. Is this a case-sensitivity issue?

It seems the opposite was applicable to other vendors (and it doesn't seem like anything other than react-native suffers from this). My only reason for pushing back against this is that react-native is the newer project and is prone to bugs and poor behavior compared to the "spec" other browsers follow.

There is no bad idea in overriding the header value since by all accounts it should be the same.

The goal of this module is not to patch up implementation issues with react-native (which this seems to be). If you can give me a good case for this not being a react-native issue then I would gladly include the check but everything I have read about how the function is suppose to behave seems to point to it returning a value if the header is present.

**Comment by alinz** [comment]
@defunctzombie thank you for clarify it. I will try to find a use case for it.
