### ISSUE TITLE
Response#setEncoding method is not available in the client build (and more)

### ISSUE THREAD

**Issue by alex94puchades** [visionmedia/superagent#729]
I'll probably make a fast PR addressing this, but the root cause remains: why there has to be two independent and (wildly) different copies of the (supposedly) same functionality? Couldn't we abstract XHR/http into a common interface and then have a common source code base? That would cut down bugs, simplify testing, make mocking easier and everybody would be happy.

**Comment by alex94puchades** [comment]
In addition to that (which was already terrible), the expected signature of the parsers ALSO VARIES!!! How am I supposed to write an isomorphic parser for superagent then?!!!

**Comment by defunctzombie** [comment]
Yes, I know. I welcome PRs that that consolidate the source code. I did not write it this way and have not had the time to allocate to re-writing it since it works.

Separately, some methods you will find are simply not available in the client (like `.agent`) because the node version can do things differently. The reality is that while same api in client and browser is a nice idea, there will always be subtle differences and that is ok.

**Comment by alex94puchades** [comment]
I'm closing this, since #690 seems like a better place to keep track of differences between the client and server builds
