### ISSUE TITLE
Customize qs.stringify options

### ISSUE THREAD

**Issue by nickclaw** [visionmedia/superagent#730]
As far as I can tell there is no way to override the options passed to `qs.stringify` in superagent. It would be helpful to be able to set those on a global or per-request basis.

Something like:
```javascript
request.qsOpts = { strictNullHandling: true };

// or

request.get('/path')
    .query({ test: null })
    .qs({ strictNullHandling: true })
    .end(done);
```

**Comment by pornel** [comment]
Correct, we don't have that option. In the browser version we use a custom minimal serialization instead of the full `qs` library, so to support customization we'd have to bundle `qs` in the browser as well. Perhaps the overhead is not too big, but I'm not sure if it's common enough use-case.

Currently you can convert object to string in your own code, using your own rules, and set query as a string.

**Comment by garrows** [comment]
Without looking deeply, I think this is out of date as superagent now requires `qs` 
https://github.com/visionmedia/superagent/commit/dc18679a7c5ccfc6046d882015e5126888973bc8#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R35
