### ISSUE TITLE
Custom Parser

### ISSUE THREAD

**Issue by jakepearson** [visionmedia/superagent#751]
I would like to pass in a parser for a request to override `JSON.parse`. If possible, I would like to change request to look something like this:

```
request
  .get('/api/pet')
  .parser(myCoolParser)
  .end(function(err, res){
    // Calling the end function will send the request
    // Now I don't need to reparse the message a second time
  });
```

Please let me know if you think this is an ok idea. I would be happy to create a pull request for it.

**Comment by limscoder** [comment]
+1

**Comment by defunctzombie** [comment]
Seems reasonable. PR would go a long way to getting the conversation going :)

**Comment by defunctzombie** [comment]
Are there any existing issues that talk about doing the same thing?

**Comment by jakepearson** [comment]
I didn't see anything like this.

**Comment by jakepearson** [comment]
@defunctzombie I attached some code. It turns out this facility is already on the node side of the library. I tried to make it similar for the client.

**Comment by alex94puchades** [comment]
There was already #742 which also added unit tests for this

**Comment by defunctzombie** [comment]
closing in favor of #742

**Comment by allthesignals** [comment]
I'd like to use this, but it seems to require the use of buffers. How would this work with try/catch? I switched to superagent to take advantage of better syntax for try/catch and exception handling (async/await).

Seems I must use `.end` to handle errors. I can understand why (flexibility for binary types or something) but it'd be nice to _extend_ an existing parser (json) so that I could still leverage modern syntax.
