### ISSUE TITLE
auth args handling different on node/browser APIs

### ISSUE THREAD

**Issue by focusaurus** [visionmedia/superagent#796]
The `request.auth()` code is slightly different between node and browser, and there's no technical reason why it couldn't be identical. In particular, the node code has a bit more automagic handling of permutations of `user, pass` arguments.

Would be straightforward to add some extra tests and get them to parity. Existing tests are pretty good so this would be a good first contribution.

**Comment by edmundoa** [comment]
I stumbled into this issue while debugging an error I'm seeing with superagent (v. 3.5.2) and I want to add a comment on it:

Due to the inconsistency described in the issue, the code handling `request.auth()` in node also throws an error if the `user` given as a first argument is `undefined`, while in the browser it works fine.

I'm willing to do a PR for this, would you consider merging it? I know the issue said it would be a good first contribution, but it's also fairly old...

Thank you in advance!

**Comment by focusaurus** [comment]
Yes I would definitely consider merging. Give it a shot and let us know if you have any questions.
