### ISSUE TITLE
How to config superagent globally

### ISSUE THREAD

**Issue by littlee** [visionmedia/superagent#820]
Is there any api method I can use to config superagent globally?
Like, set a csrf token header for every single POST request?

**Comment by pornel** [comment]
See https://www.npmjs.com/package/superagent-defaults

**Comment by MovingGifts** [comment]
@pornel Is this still the recommended way or is there something baked in the library now to allow that out of the box?

**Comment by pornel** [comment]
superagent-defaults is still the best solution.

I assume that when people want global, they mean configuring truly globally that every `require('superagent')` gives you pre-configured instance, but I'm not planning to add anything like this, because it would break libraries (if superagent is a dependency of your dependency, you'd be unexpectedly changing someone else's requests).

**Comment by MovingGifts** [comment]
Awesome, thanks for the quick response :)
