### ISSUE TITLE
Superagent 2.0

### ISSUE THREAD

**Issue by pornel** [visionmedia/superagent#854]
There are few issues/pull requests with [changes/fixes that could potentially be backwards-incompatible](https://github.com/visionmedia/superagent/labels/Semver-Major).

* Should we make a 2.0 release?
* Should we continue developing/backporting fixes to 1.x? If so, what about 0.x?
* Is it better to release all breaking changes at once in a really major 2.0, or should changes be spread to break little at a time, and be released as v2, v3, v4... v20, v21... etc.?

**Comment by focusaurus** [comment]
I can't weigh in from tons of experience on libraries of this popularity, but my gut says the substack/hammer approach of shipping semver major as often as we need is better. I think browserify has gone from v9 to v13 and I've never had to change my code. Ditto for joi.

Given this library still has a pretty big backlog of PRs and issues and a fairly small allocation of contributor attention, I don't think we're in a position to offer "long term/maintenance" releases on prior major versions. I think for the most part, stuff that's broken in v1 has probably been broken a while.

I'm OK with batching up a few issues into a single semver release if we already know about them and have a fix plan at the same time, but other than that I don't think we should hold code back more than say 2-3 weeks.

**Comment by olalonde** [comment]
Sorry, I'm a bit out of the loop here as I've been busy with other projects but I also vote for releasing major versions more often (as needed) and only consider long term maintenance if it becomes a real issue to library users.

On a related note, I'd like to propose we use babel as part of the build so we can safely start using es2015 features.

**Comment by focusaurus** [comment]
I'm -1 on babel for the node code base. I guess I'm OK with it for the browser, but I'd rather build the client via browserify sticking with ES5 as we currently do. I find needing a babel preprocessor before running code on node a major development hassle and I'd rather say this works on node directly.

**Comment by olalonde** [comment]
I was also initially skeptic at first but I have been using babel for the last few months in other projects. Also babel comes with `babel-node` which is a drop in replacement for `node` when developing. We would just need a prepublish script that runs babel before publishing to npm.

**Comment by focusaurus** [comment]
It's not that simple. You need to transpile before you can run tests or debug. You need sourcemaps. Many existing tools for debugging, linting, code coverage, etc are not babel aware yet and everything becomes slower and more complicated and confusing. All this makes babel painful for me and ES5 simple and fast. I don't think there's much in the ~3000 LoC superagent codebase that would hugely benefit from ES2015 features. Anyway, end of my opinion on that one.

**Comment by focusaurus** [comment]
I'd vote to deprecate `.then()` in 2.0 and remove in 3.0 in favor of user-choice promisification method applied to `req.end(cb)`

**Comment by pornel** [comment]
I agree with @focusaurus on Babel. Right now it feels unnecessary complication to me. I do like ES6, so perhaps we can revisit that decision later (e.g. when non-transpiled ES6 becomes viable in browsers and/or node).

**Comment by pornel** [comment]
If you mean complete removal of `.then()`, then I'm against it. While the current implementation is bad, complete removal is an unnecessary compatibility break. If we add promisification to `.end()`, we can make `.then()` call `.end().` for backwards compatibility.

**Comment by focusaurus** [comment]
OK if we can easily fix up `.then()` to have good behavior without too much
hassle, sounds good to me.

**Comment by jpodwys** [comment]
A couple of thoughts:

1- I agree with both staying with ES5 for now and with keeping `.then()` in place. I don't want the extra trouble of dealing with preprocessors and removing `.then()` just seems unnecessary at this point.

2- I know this issue mainly focuses on breaking API changes for end users and it seems there's a consensus among the few commenters here that breaking changes and therefore major releases should not be avoided. In the interest of progress, I agree. However, I would just like to say that, as the author of [superagent-cache](https://github.com/jpodwys/superagent-cache), I have greatly appreciated the complete lack of internally breaking code changes in the year since I my initial release. I know that a breaking change for an end user does not necessarily mean a breaking change for a superagent extension, but it would be nice if internal consistency was on people's minds when making publicly breaking changes.

Perhaps release candidates for breaking changes, even just internal ones, could help extension maintainers keep up. I would just hate superagent-cache's potential incompatibility with the latest major superagent release to force coders to choose between the latest superagent release and superagent-cache or any other extension that wants to keep up.

Thanks for your time and hard work!

**Comment by pornel** [comment]
@jpodwys speaking of breaking, I've just released 1.8.0 as beta. It has some internal changes to reduce code duplication as we hope it won't break anything, but we'd like feedback on that.

**Comment by jpodwys** [comment]
Thanks for the heads up! I'll try it out today. My test suite is not yet comprehensive, but I'll pin to your release and run my tests and let you know what happens.

If we discover that there is a set of common internals all extensions rely on, perhaps we can indicate that changes to those portions should be taken more seriously somehow.

**Comment by jpodwys** [comment]
It seems I spoke too soon--since `1.7.0`, my tests no longer pass. Since my library depends heavily on the inner workings of precisely how query params, headers, and other such data is stored, it can be a brittle relationship. Honestly, I'm surprised it didn't break sooner!

It appears that the changes made to how headers are stored and read in `1.7.0` are breaking superagent-cache. Below is the code I'm currently using to retrieve headers:

```javascript
getHeaderOptions: function(req){
  if(req && req.req && req.req._headers){
    return req.req._headers;
  }
  else if(req && req._header){
    return req._header;
  }
  return null;
},
```

Before `1.7.0`, this function returned the headers, but since `1.7.0`, it does not. I cannot comment on the `1.8.0` beta until I resolve the incompatibilities in earlier versions. If anyone knows, please inform me what changes. If not, I can look into the code myself.

**Comment by pornel** [comment]
1.8 changes headers again, but the good news is that it makes it consistent in browser and node. #891

**Comment by jpodwys** [comment]
OK, it appears that a change with redirects in a post-`1.7.0` release is also incompatible.

Every time an internally breaking change is made, I need to compensate for it as well and remaining backwards compatible with older versions of superagent. It just keeps adding testing time and code complexity.

I don't mean to complain--I'm happy to make superagent-cache compatible with the latest versions, but I would greatly appreciate a game plan for consistency so that I don't have to deal with incompatibilities frequently. After all, we are talking about frequent major releases. Any ideas?

**Comment by jpodwys** [comment]
I respect the fact that superagent may need to make a number of internally breaking changes in the near future. If the superagent team is able to come up with a reasonable plan for maintaining internal consistency (perhaps starting with `2.x`) while still not avoiding publicly breaking changes, I can move superagent-cache to `2.x` at the same time superagent goes to `2.x` and consider no longer supporting `1.x`.

I just don't see myself having enough time to maintain two versions of superagent-cache, much less backwards compatibility spanning numerous internally breaking changes. I'm also not thrilled with the idea of making superagent-cache compatible with > `1.6.1` until some agreement on consistency can be reached. 

Am I way off here, or does this seem reasonable? Any thoughts on a consistency strategy?

**Comment by pornel** [comment]
Last time I've looked at version stats, there still was a lot (like 1/3rd IIRC) of users on 0.x. I expect move from 1.x to 2.x to take a long time. 

OTOH we're not planning any major rewrites (the sharing of code mostly moves existing functions to one file), and the backwards compatibility API breaks we currently have in the pipeline are mostly around edge cases.

**Comment by jpodwys** [comment]
Ok thanks, that's comforting. Surprising so much of the user base is on 0.x. I don't support earlier than 1.1, I believe. At least that's where superagent was when I initially released.

**Comment by jpodwys** [comment]
I've identified a rather troubling internally breaking change introduced in `1.7.0`. Previous to `1.7.0`, headers are stored in lower case whereas in `1.7.0`, headers are stored in whatever case they were passed. I'm basing this off of the data returned from the function I pasted above titled `getHeaderOptions`.

As a result, I'm unable to support both `1.7.0` and previous versions from the same code base because there is no `version` attribute within superagent. Perhaps there should be. Additionally, it's troubling that headers undergo a `.toLowerCase()` since [headers are case-sensitive](http://stackoverflow.com/questions/5258977/are-http-headers-case-sensitive).

**Comment by focusaurus** [comment]
So prior to the change, the behavior was different in node and the browser. Now it's the same. We store both as-provided (req.header) and lowercased (req._header). When passing headers on to the underlying node/browser APIs, we use the as-provided values.

The articles and RFCs you link to, and node core's behavior indicate HTTP header names are case-insensitive.

**Comment by jpodwys** [comment]
In `1.7.0`, `req._header` is never populated until after `.end()` is called. Because I'm patching superagent to be capable of not executing an http request if data exists in the cache, this breaks me--I need to generate a cache key to perform a lookup prior to query execution. And, because I need to be backwards compatible with versions that only stored lower-case headers, I need the lower-case headers before `.end()` is called.

**Comment by jpodwys** [comment]
Also, it appears that before `.end()` is called, `"User-Agent":"node-superagent/1.7.0"` is present in the headers object but not after. This is really frustrating. What was the reasoning for changing the behavior so that request headers are not finalized until after the http call is made?

**Comment by jpodwys** [comment]
OK, I was able to get everything working with `1.6.1`, `1.7.0`, `1.7.1`, `1.7.2`, and the `1.8.0` beta release. It's currently just in a branch but I plan to merge it tomorrow. Sorry for my frustration.

**Comment by pornel** [comment]
AFAIK `toLowerCase` is correct, because header names are case **in**sensitive https://tools.ietf.org/html/rfc7230#section-3.2 (and in HTTP/2 they're not even case-preserving).

It may be a common pattern that we compute some data lazily in `.end()`. Perhaps for plugins we could add a method to precompute-data-as-if-end-happened?

**Comment by pornel** [comment]
@focusaurus should we start merging in breaking changes?

**Comment by focusaurus** [comment]
Looks like you already did, but yeah. Any thoughts on deprecating either component and/or bower support as of 2.0 so we could consider removing in some subsequent major release? I don't mind maintaining them (especially if others who are actively using them help out), but AFAIK component is pretty much abandoned/forgotten now and bower had a spike of much more popularity, but clearly is being abandoned in favor of npm going forward.

**Comment by pornel** [comment]
I haven't used component. AFAIK it's currently broken, so I wouldn't mind dropping it.

I'm OK with supporting bower in a minimal fashion - i.e. just bower.json without precompiled files polluting the repository.

**Comment by jpodwys** [comment]
@pornel I finally got around to testing superagent-cache with superagent `1.8.0`, `1.8.1`, and `1.8.2` and all my tests pass! Quite relieving since you mentioned a bit ago that `1.8.0` changed how headers were handled again.

I see that a `2.x` alpha has been released. Any new thoughts on how to approach a potential developer API? If you'd still like to do it, do you know if it will make it into `2.0.0`?

**Comment by mudrummer012** [comment]
Was alpha 3 suppose to be marked as latest in npm @pornel ?

Was a bit surprised when `npm i superagent` grabbed an alpha release this morning

**Comment by pornel** [comment]
Ouch. I it was not supposed to be latest, I forgot to tag it as next.

OTOH we haven't added anything unstable recently and haven't got reports of sky falling, so maybe we should just release it as stable?

**Comment by focusaurus** [comment]
I've had some projects update to it via `npm-check-updates`. That was a bit surprising, but no issues so far but my usage is pretty basic. I'm OK releasing it as stable. I'm not aware of any users actively installing the betas and doing explicit testing so I'm not sure we're going to get any additional feedback on the pre-releases.

**Comment by Spy-Seth** [comment]
I use the alpha from some time now, and no issue on my side. 

:+1: for release.

**Comment by pornel** [comment]
And it's done!

Big thanks to everyone who contributed.
