### ISSUE TITLE
HTTP status 204 with a content-encoding: gzip

### ISSUE THREAD

**Issue by vicanso** [visionmedia/superagent#857]
HTTP endpoint that returns a 204 with a `content-encoding: gzip`, it will throw Error `[Error: unexpected end of file] errno: -5, code: 'Z_BUF_ERROR'`.

**Comment by yourcontainer** [comment]
+1

**Comment by focusaurus** [comment]
Perhaps we can sanity check `Content-Length` header before unzipping? In node I think we just `.pipe()` into a zlib stream but perhaps that doesn't handle zero-size payload properly. Anyone care to code a unit test and a fix and submit a pull request?

**Comment by sheltonial** [comment]
+1

**Comment by hustcer** [comment]
+

**Comment by pornel** [comment]
I can't fix this without more information. Please don't +1, as this does not help at all.

Please submit unit tests or a full dump of server and client HTTP headers.

**Comment by hustcer** [comment]
@pornel Sorry, I will add more info later.

**Comment by seangarner** [comment]
I doubt this is the cause, but just in case....

A number of conditionals aren't triggered if instantiating the `Request` class directly with a lowercase method.  See visionmedia/supertest/pull/371 for an example of how superagent is doing just this and ending up with the same zlib error as in this issue.

@pornel I'm not sure if you'd consider this a superagent bug or not.  Personally I think it is because the  `Request` class is exported and documented yet methods are only uppercased when calling the function.  If you agree I can open a PR for that.

**Comment by hustcer** [comment]
Just run the following code:
```
const request = require('superagent');

request
    .get('http://www.dfzq.com.cn/dfzq/dfyw/rzrqbdzq.jsp')
    .buffer()
    .end((err, res) => {

        console.log(err, res);
    });
```
and you will get the error:
```
{ Error: unexpected end of file
    at Zlib._handle.onerror (zlib.js:370:17) errno: -5, code: 'Z_BUF_ERROR', response: null } null
```

**Comment by pornel** [comment]
Thanks for the test case with `dfzq.com.cn`. That helped me diagnose and fix the problem.

**Comment by hustcer** [comment]
@pornel Great !
