### ISSUE TITLE
Inconsistent get-header method for Request in Node and browser

### ISSUE THREAD

**Issue by xhh** [visionmedia/superagent#873]
In the browser version's Request function, there's a `getHeader` method to get a request header (that might be set before), and the Node version uses a `get` method for the same purpose.
It would be better to use a consistent name.

**Comment by focusaurus** [comment]
Agree. I will tackle this as part of #830.

Personally I think names like `get`, `set`, `data`, `field` while concise, are unclear and if I were to design this library from scratch I would replace generic works with correct and specific http words (header, body, etc) and opt for obviousness vs conciseness (so `getHeader` instead of `get`). **However** this library and a lot of TJ's libraries (express, mongoose) do use the super-concise ones, so it seems best to maybe maintain that consistently.

So I'd probably vote to just go with `get` and `set` being the consistent superagent API for headers, leave `getHeader` implemented as an alias for backward compatibility, but perhaps deprecate it in the next semver major.

**Comment by focusaurus** [comment]
Also according to the API javadoc, `getHeader` is a private API and `get`/`set` are the public APIs your code should be using.
