### ISSUE TITLE
1.8.0 broke component support

### ISSUE THREAD

**Issue by stephenmathieson** [visionmedia/superagent#931]
we're still still using component/duo in a few places and 1.8.0 broke component support.

there's no "form-data" dep in `component.json` so we die with:

```
Uncaught Error: cannot find module "form-data"
```

**Comment by pornel** [comment]
Oh, probably bower has the same problem. I forgot we have non-npm manifests.

**Comment by pornel** [comment]
I haven't used component before. Can it install npm packages? Could you make a pull request with dependency declaration it needs?

**Comment by focusaurus** [comment]
Requesting help from anyone more familiar with componentjs. How does this interact with browserify/npm? Should we be building a superagent.js file with browserify and checking that into the master branch and referencing that from component.json? Do we need to roll back this change and make sure the browser implementation uses only in-repo deps or deps that have component support?

@airportyh @jongleberry-bot @matthewmueller ?

**Comment by airportyh** [comment]
As I understand it, each componentjs dep and transitive deps need to be proper componentjs projects. My feeling is if you want to use form-data or any other module that doesn't support componentjs (quick check is to see if it has a component.json), it will not be worth the trouble to support componentjs, because

1. componentjs is a deprecated project
2. the amount of work to get all deps and transitive deps working with componentjs and the resistance you'll get trying to convince the authors to support a deprecated project

**Comment by pornel** [comment]
I think we can fix component support for 1.9.0 (we can avoid using form-data client-side #941), but we'll drop component support in 2.0.

**Comment by pornel** [comment]
1.8.2 makes form-data optional on client-side, so should work again
