### ISSUE TITLE
Using superagent with bower

### ISSUE THREAD

**Issue by chrisdchristo** [visionmedia/superagent#936]
Hey I'm trying to use v1.8.0 with bower. After installing it with bower I don't know which js file I am supposed to include in my project. Before in older versions there was the file `/bower_components/superagent/superagent.min.js` but that doesn't exist no more. Please advise.

**Comment by chrischristo** [comment]
Also in general with the releases here, where are the final production files? I would expect a ```superagent.js``` and a ```superagent.min.js``` file included in the artifacts in the github releases. But alas all I see is source code zips and tars. Seriously?

**Comment by pornel** [comment]
Sorry, our Bower support is minimal.

We don't check in autogenreated files into git repository, because they cause merge conflicts. For npm we generate `superagent.js` that is included in the archive, but I don't know if that is possible for Bower without polluting our github repo.

Without the precompiled file, we assume you'd use something like WebPack or Browserify and `require('superagent')` in your code.

**Comment by zallek** [comment]
Hi could you release with the fix on bower.json pls ?
https://github.com/visionmedia/superagent/commit/47b44ac55a960136b23e4b3baca054365adb7ee3

**Comment by pornel** [comment]
done

**Comment by zallek** [comment]
thx :)

**Comment by Eiskis** [comment]
Could you elaborate the intended and non-intended usage in the readme? I'm also running into this, as my project does not use WebPack or Browserify. I saw in another discussion you suggested using wzrd.in, so maybe you could add that to the readme?

I understand that moving to a pipeline that supports using superagent as in your current examples is the preferred way of using the library, but in real life this is not always possible when integrating with projects. It doesn't make sense to simply not provide any information on the subject to the users in my opinion.

**Comment by pornel** [comment]
AFAIK Bower doesn't support bundling of pre-compiled files (apart from working around it by polluting source code repository with generated files), so with Bower you have no choice but use WebPack or Browserify or such.

However, if you use `npm` instead you can get a pre-compiled standalone browser version of superagent. It'll be installed in `node_modules/superagent/superagent.js`.

**Comment by ramukaka30091993** [comment]
Without bower support, the libraries using superagent as their hard dependency cannot resolve dependencies only using bower. They would have to use other ways to resolve these dependencies. Like every other JS based library providing a folder containing **superagent.js** and a **superagent.min.js** on bower and git would have been really helpful

**Comment by sajalrustagi** [comment]
Without bower support, the libraries using superagent as their hard dependency cannot resolve dependencies only using bower. They would have to use other ways to resolve these dependencies. Like every other JS based library providing a folder containing **superagent.js** and a **superagent.min.js** on bower and git would have been really helpful

**Comment by pornel** [comment]
git repository shouldn't contain derived files, especially when they're unmergeable. I'd prefer not to add such files just because Bower is confuses *source code* with a built product.

My suggestions:

1. Consider abandoning Bower. NPM 3 has a flat directory structure. Yarn has `--flat` switch that enforces Bower-like version resolution.

2. If you have to use Bower, use build tools like Gulp and Webpack that will build and minify superagent's source for you. 

3. If you really have to use Bower and can't have a build step, fork this repository and add and maintain the derived files yourself.
