### ISSUE TITLE
Saucelabs + localtunnel setup degraded to the point of being unusable

### ISSUE THREAD

**Issue by pornel** [visionmedia/superagent#972]
Our CI on travis keeps failing due to flakyness of the browser tests.

It used to be flaky, but now 2-3 browsers fail so frequently, that it's really hard to get a build pass, and it's blocking PRs. 

Increasing timeouts doesn't help much.
- Are there any Zuul/Saucelabs settings that we can change to improve reliability?
- Would it help to split the tests or drop some browsers?
- Can we do something about localtunnel.me refusing connections? Could it also be responsible for the timeouts?

**Comment by pornel** [comment]
@defunctzombie is localtunnel.me overloaded or having some connectivity issues? We're seeing denied connections and data timing out so frequently, that the tests almost always fail.

Should we host our own localtunnel server?

**Comment by focusaurus** [comment]
If we just need a daemon I have Ubuntu x64 droplets in digital ocean SFO1 I can easily run something (docker or debian/ubuntu package) and could set up a DNS name for it.

**Comment by focusaurus** [comment]
For a while now it seems like our CI stack is unable to consistently pass test builds. I'm filing this issue to try to figure out exactly what the issue(s) are and see if it can be fixed.

First, some notes on how things work as I understand them:

- Key files are `Makefile`, `.travis.yml`, `.zuul.yml`
- Automated CI test builds are run by Travis CI whenever a pull request is created or updated
- Travis runs the same test suite in several environments including node versions 0.12, 4.6, and 6.7
- The node tests on Travis seem stable and consistently pass
- One configuration travis runs sets `BROWSER=1` to trigger saucelabs automated browser testing
  - This is handled via `zuul` and amounts to
  - starting up a local express server on the travis worker instance
  - using zuul to open up a port on localtunnel.me so that local express instance is Internet-accessible
  - launching a suite of saucelabs headless/automated browser tests running the superagent client tests pointing at the localtunnel URL
  - In Travis, I think we experience 3 types of failures
   - Some saucelabs OS/browser combos fail by exceeding a 2s timeout
   - Some saucelabs OS/browser combos fail by exceeding a 10s timeout
   - Some saucelabs fail with connection refused from travis worker out to localtunnel


## Local Behavior

- Trying to run `make test-browser` from my laptop seems to start/wait/restart saucelabs instances for a very very long (forever?) time. Many many minutes go by without seeing any successful runs.


## Open Questions

- Why don't the zuul/saucelabs tests work when run locally?
- Why do the zuul/saucelabs tests fail when run within Travis?
- Should we consider switching to [the Travis Sauce Connect Addon](https://docs.travis-ci.com/user/sauce-connect/)?
- Should we switch to a saucelabs alternative?

**Comment by focusaurus** [comment]
I deployed my own localtunnel server today, verified it worked for a normal express app, then tried to run the superagent browser tests through it. Still hanging waiting for saucelabs to actually start running any browser tests. I think I'm going to open up a support case with saucelabs and see if they are willing and able to help troubleshoot this.

**Comment by focusaurus** [comment]
Will keep an eye on travis runs as new PRs come in to see if GH-1103 makes things reliable enough.

**Comment by pornel** [comment]
Works well now!
